.PHONY: test readme pre-commit check-readme

install:
	uv sync --all-extras

test:
	uv run pytest

readme:
	rm -rf README_files
	uv run jupyter nbconvert --to markdown README.ipynb
	@{ echo "<!-- ⚠️ DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED FROM README.ipynb ⚠️ -->"; cat README.md; } > README.md.tmp && mv README.md.tmp README.md

pre-commit:
	uv run pre-commit run --all-files

check-readme: readme
	git diff --exit-code README.md
